#:schema node_modules/wrangler/config-schema.json
name = "my-chat"
compatibility_date = "2024-11-11"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[env.production.ai]
binding = "AI"

[env.production.vars]
ENVIRONMENT = "production"
